
version: '2'
services:

  odoo:
    image: odoo:8.0
    container_name: odoo8
    ports:
      - "8069:8069"
    restart: always
    environment:
      PGHOST: db
      PGUSER: odoo
      PGPASSWORD: odoo
    volumes:
      - ./extra_addons:/mnt/extra-addons
    depends_on:
      - db
    links:
      - db
  
  db:
    image: postgres:9.4
    container_name: odoo8-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes_from:
      - db_data
    restart: always
  
  db_data:
    image: busybox
    container_name: odoo8-db_data
    volumes:
      - ./docker_data/db:/var/lib/postgresql/data
    restart: always

  odoo8_data:
    image: busybox
    container_name: odoo8_data
    volumes:
      - ./docker_data/extra_addons:/mnt/extra-addons
      #- ./docker_data/config:/etc/odoo
    restart: always